kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clo835-rolebinding
  namespace: final 
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
roleRef:
  kind: Role
  name: CLO835
  apiGroup: rbac.authorization.k8s.io
