apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: final
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mysql-db
        image: us-east1-docker.pkg.dev/kubernetes-app-398819/database-image/my-sql:1.0
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: sqldb-data
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: DBPWD 
      volumes:
        - name: sqldb-data
          persistentVolumeClaim:
            claimName: sql-data-claim
      imagePullSecrets:
        - name: regcred
